name: Cherry-pick PR into release branches

on: issue_comment

jobs:
  cherry_pick_release_blue:
    runs-on: ubuntu-20.04
    name: Cherry pick into release-blue
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'cherry-pick release-blue') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Cherry-pick changes
        id: cherry-pick
        run: |
          git config user.name ${{ github.event.issue.user.login }}
          git config user.email ${{ github.event.issue.user.login }}@users.noreply.github.com
          git fetch origin pull/${{ github.event.issue.number }}/head:temporary_pr_${{ github.event.issue.number }}_branch
          git checkout release-blue
          commits=$(git rev-list master..temporary_pr_${{ github.event.issue.number }}_branch | sed '1!G;h;$!d')
          echo "Cherry-picking commits: $commits"
          git cherry-pick $(echo $commits | xargs | sed 's/ / /g')
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: |
            Cherry-pick PR #${{ github.event.issue.number }} into release-blue
          body: |
            Perform a release of the changes in PR #${{ github.event.issue.number }}

            Note: This is an auto-generated PR.
          base: release-blue
          branch: cherry_pick_pr_${{ github.event.issue.number }}_to_release_blue
