name: Cherry-pick PR into release branches

on: issue_comment

jobs:
  cherry_pick_release_blue:
    runs-on: ubuntu-20.04
    name: Cherry pick into release-blue
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'cherry-pick release-blue') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cherry-pick changes
        id: cherry-pick
        run: |
          git fetch origin pull/${{ github.event.issue.number }}/head:temporary_pr_${{ github.event.issue.number }}_branch
          git checkout release-blue
          git checkout -b cherry_pick_pr_${{ github.event.issue.number }}_to_release_blue
          git rev-list master..temporary_pr_${{ github.event.issue.number }}_branch
